# Generated by Django 5.1.4 on 2024-12-30 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('job_title', models.CharField(blank=True, max_length=50)),
                ('years_of_working', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('hire_date', models.DateTimeField(auto_now_add=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('designation', models.CharField(choices=[('E', 'Employee'), ('H', 'HR Manager'), ('A', 'Admin')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
